

plot:
	nalu-forces ./static_polar_2d_rans/*.csv --polar-ref ./ref/cfd_re3M.csv --yaml ./static_polar_2d_rans/input.yaml --polar-exp ./ref/exp_re3M.csv

plotturb:
	nalu-forces ./static_polar_2d_rans_ori_turb/*.csv --polar-ref ./ref/cfd_re3M.csv --yaml ./static_polar_2d_rans/input.yaml --polar-exp ./ref/exp_re3M.csv
