""" 

CSV Polars are generated by t15_polar_postpro.py

Here we generate AD files

"""

import matplotlib.pyplot as plt
import numpy as np
from welib.airfoils.Polar import Polar
import welib.weio as weio
import glob
import os
import re
from welib.essentials import *

csvDir = '_results/_polars/'
ADDir = '_results/_polars_AD/'

os.makedirs(ADDir, exist_ok = True)

files = glob.glob(csvDir + '*.csv')
# print(files)
for f in files:
    print('\nt16: Opening:', f)
    basename = os.path.basename(f)
    ADfilename = os.path.join(ADDir, basename.replace('.csv' ,'.dat'))
    pol = Polar(filename=f)
    if np.all(np.isnan(pol.cm)):
        #WARN('Cm is Nan, replacing with 0')
        pol.cm[:] = 0
    Re = float(re.search(r"re([0-9.]+)", basename).group(1))
    if 'exp' in basename.lower():
        if all(s not in basename for s in ('du00-w-212', 'nlf1-0416', 'ffa-w3')):
            comment = 'Experimental data from OSU database'
        else:
            comment = 'Experimental data as used in Exawind benchmark'
    else:
        if 'cfd2d' in basename.lower():
            comment = 'Obtained using NALU-Wind - CFD 2D RANS'
        else:
            comment = 'Obtained using NALU-Wind - CFD 3D IDDES'
    comment += f'\nSource File: {basename}'
   
    #pol.unsteadyParams()
    pol.toAeroDyn(ADfilename, comment=comment, Re=Re)
    if 'cfd' in basename.lower()  and '_n' in basename.lower():
        iLow  = np.argmin(np.abs(pol.alpha+2.8))
        iHigh = np.argmin(np.abs(pol.alpha-7.0))
        alpha = pol.alpha
        cl = pol.cl
        if cl[iLow]>0 and iLow>0:
            iLow=iLow-1
        cd = pol.cd
        cm = pol.cm
        a0, a1 = pol.alpha[iLow], pol.alpha[iHigh]
        cl0, cl1 = pol.cl[iLow], pol.cl[iHigh]

        cl_alpha = (cl1 - cl0) / (a1 - a0)   # slope
        cl_at_0 = cl0 - cl_alpha * a0               # intercept
        alpha0 = -cl_at_0 / cl_alpha

        alpha_lin = np.arange(a0, a1 + 1e-12, 0.5)
        cl_lin = np.interp(alpha_lin, [a0, a1], [pol.cl[iLow], pol.cl[iHigh]])
        cd_lin = np.interp(alpha_lin, pol.alpha, pol.cd)
        cm_lin = np.interp(alpha_lin, pol.alpha, pol.cm)

        # concatenate full polars
        alpha_new = np.concatenate([[-180], pol.alpha[:iLow], alpha_lin, pol.alpha[iHigh+1:], [180]])
        cl_new   = np.concatenate ([[ -0.0001], pol.cl[:iLow], cl_lin, pol.cl[iHigh+1:]     , [  0.0001]])
        cd_new   = np.concatenate ([[ -0.0001], pol.cd[:iLow], cd_lin, pol.cd[iHigh+1:]     , [  0.0001]])
        cm_new   = np.concatenate ([[ -0.0001], pol.cm[:iLow], cm_lin, pol.cm[iHigh+1:]     , [  0.0001]])

#         try:
        pol2 = Polar(cl=cl_new, cd=cd_new, cm=cm_new, alpha=alpha_new, Re=Re)
        pol2.toAeroDyn(ADfilename.replace('.dat', '_extraLin.dat'), comment=comment, Re=Re)
        comment  += f'\nMaking Cl linear by focusing on values at alpha= {a0} {a1}'
#         except:
#             import pdb; pdb.set_trace()
#         comment  += f'\nMaking Cl linear by focusing on values at alpha= {a0} {a1} - Full polar extrapolation'
#         pol3.toAeroDyn(ADfilename.replace('.dat', '_extraLin_full.dat'), comment=comment, Re=Re)


