""" 

CSV Polars are generated by t15_polar_postpro.py

Here we generate AD files

"""


import numpy as np
from welib.airfoils.Polar import Polar
import welib.weio as weio
import glob
import os
import re
from welib.essentials import *

csvDir = '_results/_polars/'
ADDir = '_results/_polars_AD/'

os.makedirs(ADDir, exist_ok = True)

files = glob.glob(csvDir + '*.csv')
print(files)
for f in files:
    print(f)
    basename = os.path.basename(f)
    ADfilename = os.path.join(ADDir, basename.replace('.csv' ,'.dat'))
    pol = Polar(filename=f)
    if np.all(np.isnan(pol.cm)):
        WARN('Cm is Nan, replacing with 0')
        pol.cm[:] = 0
    Re = float(re.search(r"re([0-9.]+)", basename).group(1))
    if 'exp' in basename.lower():
        if all(s not in basename for s in ('du00-w-212', 'nlf1-0416', 'ffa-w3')):
            comment = 'Experimental data from OSU database'
        else:
            comment = 'Experimental data as used in Exawind benchmark'
    else:
        if 'cfd2d' in basename.lower():
            comment = 'Obtained using NALU-Wind - CFD 2D RANS'
        else:
            comment = 'Obtained using NALU-Wind - CFD 3D IDDES'
    comment += f'\nSource File: {basename}'

    pol.toAeroDyn(ADfilename, comment=comment, Re=Re)
