""" 
CSV Polars are generated by t11_polar_postpro.py
AD  Polars are generated by t14_createAD.py

"""



import json
from helper_functions import load_json_chirp


# --------------------------------------------------------------------------------}
# --- MAIN SCRIPTS
# --------------------------------------------------------------------------------{
# --- Main inputs
# res_dir = '_results'
# out_dir = '_results/_chirp/'
# figout_dir = '_results/_figs_chirp/'

cases=[]
cases+=[{'airfoil_name':'S809'      , 'n':24, 're':0.8}]
cases+=[{'airfoil_name':'du00-w-212', 'n':4 , 're':3}]
cases+=[{'airfoil_name':'du00-w-212', 'n':22, 're':3}]
cases+=[{'airfoil_name':'nlf1-0416' , 'n':24, 're':4}]
cases+=[{'airfoil_name':'ffa-w3-211', 'n':24, 're':10}]

# for cs in cases[0:0]:
for cs in [cases[0]]:
    print(f"------------------------- {cs['airfoil_name']} - n={cs['n']}")

    chord=1
    span=4

    yml_path  = './_results/cases_chirp_n{}/{}/{}_re{:04.1f}_mean00_A01.yaml'.format(cs['n'], cs['airfoil_name'], cs['airfoil_name'], cs['re'])
    csv_path  = './_results/cases_chirp_n{}/{}/forces_{}_re{:04.1f}_mean00_A01.csv'.format(cs['n'], cs['airfoil_name'], cs['airfoil_name'], cs['re'])
    print('YML:', yml_path)
    print('CSV:', csv_path)

    # json_path = './_results/cases_chirp_n24/S809/S809_re00.8_mean00_A01.json'

    json_path  = yml_path.replace('.yaml','.json')
    dvr_path  = yml_path.replace('.yaml', '.dvr')
    pol_path = 


    # ---
    info, dfc    = load_json_chirp(json_path, verbose = False, plot = False)
    #df_chirp = pd.DataFrame(data=np.column_stack([t_chirp, np.degrees(theta_chirp)]), columns=['Time_[s]','angle_[deg]'])

    exe = './_templates/UADVR/UnsteadyAero_Driver_x64.exe'
    dvr = './_templates/UADVR/S809.dvr'
    dvr = TemplatedUAAdvr(dvr_template=dvr, exe=exe)

    dvr['Chord']  = info['chord']
    dvr['FldDens']  = info['density']
    dvr['KinVisc']  = info['viscosity']
    dvr['Inflow'] = [0, info['U']]
    dvr['Vec_AQ'] = [0, 0] # from "A" to aerodynamic center Q. If "A" is at mid chord values are likely (0, -0.25) (-)
    dvr['Vec_AT'] = [0, 0.5] # from "A" to three-quarter chord "T". If "A" is at mid chord values are likely (0, 0.25) (-)

    sc=4
    dvr['GFScalingL1'] = [sc, 0.0, 0.0]
    dvr['GFScalingL2'] = [0.0, sc, 0.0]
    dvr['GFScalingL3'] = [0.0, 0.0, sc]


    print(dfc.keys())
    dvr.setPrescribedPitchMotion(t=dfc['Time_[s]'], theta = dfc['angle_[deg]']*np.pi/180, dt=info['dt'])
#     dvr['SimMod'] = 2
#     print(dvr)
    dvr.run('./_templates/test/S809.dvr', verbose=True)

    print(dvr)
    if (np.abs(dvr.re)-info['re']*1e6)>100:
        raise Exception('Problem in Re')
    print(info)
