""" 
CSV Polars are generated by t11_polar_postpro.py
AD  Polars are generated by t14_createAD.py

"""
import numpy as np
import os
import json

from welib.weio.fast_input_file import FASTInputFile, ADPolarFile
from welib.weio.fast_output_file import FASTOutputFile
from nalulib.nalu_input import NALUInputFile

from UAAdvr import TemplatedUAAdvr

from helper_functions import load_json_chirp



# --------------------------------------------------------------------------------}
# --- MAIN SCRIPTS
# --------------------------------------------------------------------------------{
# --- Main inputs
# res_dir = '_results'
# out_dir = '_results/_chirp/'
# figout_dir = '_results/_figs_chirp/'
ADDir        = '_results/_polars_AD/'
exe          = './_templates/UADVR/UnsteadyAero_Driver_x64.exe'
dvr_template = './_templates/UADVR/S809.dvr'


cases=[]
cases+=[{'airfoil_name':'S809'       , 'n':24 , 're':0.8 , 'suffix':''    }]
cases+=[{'airfoil_name':'S809'       , 'n':24 , 're':0.8 , 'suffix':'_HR' }]
cases+=[{'airfoil_name':'du00-w-212' , 'n':4  , 're':3   , 'suffix':''    }]
cases+=[{'airfoil_name':'du00-w-212' , 'n':22 , 're':3   , 'suffix':''    }]
cases+=[{'airfoil_name':'nlf1-0416'  , 'n':24 , 're':4   , 'suffix':''    }]
cases+=[{'airfoil_name':'ffa-w3-211' , 'n':24 , 're':10  , 'suffix':''    }]
cases+=[{'airfoil_name':'ffa-w3-211' , 'n':24 , 're':10  , 'suffix':'_HR' }]

# for cs in cases[0:0]:
# for cs in [cases[0]]:
for cs in cases:
    airfoil_name = cs['airfoil_name']
    re           = cs['re']
    n            = cs['n']
    suffix       = cs['suffix']
    if airfoil_name == 'ffa-w3-211':
        base = airfoil_name + '_re{:05.2f}M'.format(re) + '_CFD2D'
    elif n==22:
        base = airfoil_name + '_re{:05.2f}M'.format(re) + '_CFD3D_n{}'.format(24)
    else:
        base = airfoil_name + '_re{:05.2f}M'.format(re) + '_CFD3D_n{}'.format(cs['n'])
    print(f"------------------------- {base}-------------")

    chord=1
    span=4

    yml_path  = '_results/cases_chirp_n{}/{}/{}_re{:04.1f}_mean00_A01{:s}.yaml'.format(cs['n'], cs['airfoil_name'], cs['airfoil_name'], cs['re'], cs['suffix'])
    csv_path  = '_results/cases_chirp_n{}/{}/forces_{}_re{:04.1f}_mean00_A01{:s}.csv'.format(cs['n'], cs['airfoil_name'], cs['airfoil_name'], cs['re'], cs['suffix'])
    json_path = yml_path.replace('.yaml','.json')
    dvr_path  = yml_path.replace('.yaml', '_UAA.dvr')
    cfd_outb  = yml_path.replace('.yaml', '_CFD.outb')
    uaa_outb  = dvr_path.replace('.dvr', '.outb')
    pol_path  = os.path.join(ADDir, base+'.dat')
    
    print('YML:', yml_path)
    print('CSV:', csv_path)
    print('POL:', pol_path)
    if not  os.path.exists(pol_path):
        raise Exception('Pol not found: ', pol_path)

    # --- JSON Info
    info, dfc    = load_json_chirp(json_path, verbose = False, plot = False)

    # --- Postpro yml
    yml2_path  = yml_path.replace('.yaml','_no_motion.yaml')
    if os.path.exists(yml2_path):
        print('[INFO] loading yaml without motion')
        yml = NALUInputFile(yml2_path, chord = chord, span = span)
    else:
        print('[INFO] Reading full yaml and saving with no motion')
        yml = NALUInputFile(yml_path, chord = chord, span = span)
        yml.save_no_motion(yml2_path)
        #dfm = yml.extract_mesh_motion()
    if (np.abs(yml.Reynolds)-info['re']*1e6)>100:
        raise Exception('Problem in Re yml/json')
    if (np.abs(yml.density)-info['density'])>1e-5:
        raise Exception('Problem in density yml/json')
    if (np.abs(yml.viscosity)-info['viscosity'])>1e-5:
        raise Exception('Problem in viscosity yml/json')

    # --- Postprocessing CFD forces, putting it in a format like UA driver
    vel = yml.velocity
    dff, Fref, _ = yml.read_surface_forces()
    dff = dff.rename(columns={"Time": "Time_[s]"})
    dff['Vundx_[m/s]'] = vel[1]
    dff['Vundy_[m/s]'] = vel[0]
    dff['L_[N/m]'] = dff['Fy']/span
    dff['D_[N/m]'] = dff['Fx']/span
    dff['Cl_[-]'] = dff['Cy']
    dff['Cd_[-]'] = dff['Cx']
    dff['Cn_[-]'] = dff['Cy']
    dff['Cc_[-]'] = dff['Cx']
    dff['fy_[N]'] = dff['Fx']
    dff['fx_[N]'] = dff['Fy']
    del dff['Fx']
    del dff['Fy']
    # Problem due to ffa
    if 'ffa' in yml_path:
        dt = info['dt']
        dff1 = dff.sort_values("Time_[s]").reset_index(drop=True)
        dff2 = dff1.loc[dff1["Time_[s]"].diff().fillna(dt) > dt/2].reset_index(drop=True)
        dff = dff2
    # Angle
    dfc2 = dfc[dfc['Time_[s]']<=dff['Time_[s]'].values[-1]+info['dt']/2]
    if len(dfc2)!=len(dff):
        import pdb; pdb.set_trace()
        raise Exception('Problem len of dfc')
    dff['Alpha_[deg]'] = -dfc2['angle_[deg]'].values
    dff['th_[rad]'] = np.radians(dfc2['angle_[deg]'].values)

    FASTOutputFile().writeDataFrame(df=dff, filename = cfd_outb)
    print('Writting: ', cfd_outb)
    remaining = (dff['Time_[s]'].values[-1]-info['t_total'])/info['dt']
    if remaining > 0.1:
        WARN('Incomplete CFD file')


    # --- UA
    adpol = ADPolarFile(pol_path)
    #print(adpol)
    dvr = TemplatedUAAdvr(dvr_template=dvr_template, exe=exe, dat=pol_path)
    dvr.dvr_filename = dvr_path
    #dvr.set_polar(pol_path)

    dvr['Chord']  = info['chord']
    dvr['FldDens']  = info['density']
    dvr['KinVisc']  = info['viscosity']
    dvr['Inflow'] = [0, info['U']]
    dvr['Vec_AQ'] = [0, 0]   # (0, -0.25) (-)
    dvr['Vec_AT'] = [0, 0.5] # (0,  0.25) (-)
    sc=4
    dvr['GFScalingL1'] = [sc, 0.0, 0.0]
    dvr['GFScalingL2'] = [0.0, sc, 0.0]
    dvr['GFScalingL3'] = [0.0, 0.0, sc]
    dvr.setPrescribedPitchMotion(t=dfc['Time_[s]'], theta = dfc['angle_[deg]']*np.pi/180, dt=info['dt'])

    dvr.run(dvr_path, verbose=True)
    if (np.abs(dvr.re)-info['re']*1e6)>100:
        raise Exception('Problem in Re')
#     print(info)
#     print(dvr)
